<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('iso');
            $table->string('name');
            $table->string('country');
            $table->string('iso3')->nullable();
            $table->smallInteger('numcode')->nullable();
        });

        // Insert some stuff
        DB::table('countries')->insert(array(
            array('id' => 1, 'iso'   => 'BD', 'name' => 'BANGLADESH', 'country'                                   => 'Bangladesh', 'iso3'                                   => 'BGD', 'numcode' => 50),
            array('id' => 2, 'iso'   => 'AE', 'name' => 'UNITED ARAB EMIRATES', 'country'                         => 'United Arab Emirates', 'iso3'                         => 'ARE', 'numcode' => 784),
            array('id' => 3, 'iso'   => 'AF', 'name' => 'AFGHANISTAN', 'country'                                  => 'Afghanistan', 'iso3'                                  => 'AFG', 'numcode' => 4),
            array('id' => 4, 'iso'   => 'AG', 'name' => 'ANTIGUA AND BARBUDA', 'country'                          => 'Antigua and Barbuda', 'iso3'                          => 'ATG', 'numcode' => 28),
            array('id' => 5, 'iso'   => 'AI', 'name' => 'ANGUILLA', 'country'                                     => 'Anguilla', 'iso3'                                     => 'AIA', 'numcode' => 660),
            array('id' => 6, 'iso'   => 'AL', 'name' => 'ALBANIA', 'country'                                      => 'Albania', 'iso3'                                      => 'ALB', 'numcode' => 8),
            array('id' => 7, 'iso'   => 'AM', 'name' => 'ARMENIA', 'country'                                      => 'Armenia', 'iso3'                                      => 'ARM', 'numcode' => 51),
            array('id' => 8, 'iso'   => 'AN', 'name' => 'NETHERLANDS ANTILLES', 'country'                         => 'Netherlands Antilles', 'iso3'                         => 'ANT', 'numcode' => 530),
            array('id' => 9, 'iso'   => 'AO', 'name' => 'ANGOLA', 'country'                                       => 'Angola', 'iso3'                                       => 'AGO', 'numcode' => 24),
            array('id' => 10, 'iso'  => 'AQ', 'name' => 'ANTARCTICA', 'country'                                   => 'Antarctica', 'iso3'                                   => NULL, 'numcode'  => NULL),
            array('id' => 11, 'iso'  => 'AR', 'name' => 'ARGENTINA', 'country'                                    => 'Argentina', 'iso3'                                    => 'ARG', 'numcode' => 32),
            array('id' => 12, 'iso'  => 'AS', 'name' => 'AMERICAN SAMOA', 'country'                               => 'American Samoa', 'iso3'                               => 'ASM', 'numcode' => 16),
            array('id' => 13, 'iso'  => 'AT', 'name' => 'AUSTRIA', 'country'                                      => 'Austria', 'iso3'                                      => 'AUT', 'numcode' => 40),
            array('id' => 14, 'iso'  => 'AU', 'name' => 'AUSTRALIA', 'country'                                    => 'Australia', 'iso3'                                    => 'AUS', 'numcode' => 36),
            array('id' => 15, 'iso'  => 'AW', 'name' => 'ARUBA', 'country'                                        => 'Aruba', 'iso3'                                        => 'ABW', 'numcode' => 533),
            array('id' => 16, 'iso'  => 'AZ', 'name' => 'AZERBAIJAN', 'country'                                   => 'Azerbaijan', 'iso3'                                   => 'AZE', 'numcode' => 31),
            array('id' => 17, 'iso'  => 'BA', 'name' => 'BOSNIA AND HERZEGOVINA', 'country'                       => 'Bosnia and Herzegovina', 'iso3'                       => 'BIH', 'numcode' => 70),
            array('id' => 18, 'iso'  => 'BB', 'name' => 'BARBADOS', 'country'                                     => 'Barbados', 'iso3'                                     => 'BRB', 'numcode' => 52),
            array('id' => 19, 'iso'  => 'AD', 'name' => 'ANDORRA', 'country'                                      => 'Andorra', 'iso3'                                      => 'AND', 'numcode' => 20),
            array('id' => 20, 'iso'  => 'BE', 'name' => 'BELGIUM', 'country'                                      => 'Belgium', 'iso3'                                      => 'BEL', 'numcode' => 56),
            array('id' => 21, 'iso'  => 'BF', 'name' => 'BURKINA FASO', 'country'                                 => 'Burkina Faso', 'iso3'                                 => 'BFA', 'numcode' => 854),
            array('id' => 22, 'iso'  => 'BG', 'name' => 'BULGARIA', 'country'                                     => 'Bulgaria', 'iso3'                                     => 'BGR', 'numcode' => 100),
            array('id' => 23, 'iso'  => 'BH', 'name' => 'BAHRAIN', 'country'                                      => 'Bahrain', 'iso3'                                      => 'BHR', 'numcode' => 48),
            array('id' => 24, 'iso'  => 'BI', 'name' => 'BURUNDI', 'country'                                      => 'Burundi', 'iso3'                                      => 'BDI', 'numcode' => 108),
            array('id' => 25, 'iso'  => 'BJ', 'name' => 'BENIN', 'country'                                        => 'Benin', 'iso3'                                        => 'BEN', 'numcode' => 204),
            array('id' => 26, 'iso'  => 'BM', 'name' => 'BERMUDA', 'country'                                      => 'Bermuda', 'iso3'                                      => 'BMU', 'numcode' => 60),
            array('id' => 27, 'iso'  => 'BN', 'name' => 'BRUNEI DARUSSALAM', 'country'                            => 'Brunei Darussalam', 'iso3'                            => 'BRN', 'numcode' => 96),
            array('id' => 28, 'iso'  => 'BO', 'name' => 'BOLIVIA', 'country'                                      => 'Bolivia', 'iso3'                                      => 'BOL', 'numcode' => 68),
            array('id' => 29, 'iso'  => 'BR', 'name' => 'BRAZIL', 'country'                                       => 'Brazil', 'iso3'                                       => 'BRA', 'numcode' => 76),
            array('id' => 30, 'iso'  => 'BS', 'name' => 'BAHAMAS', 'country'                                      => 'Bahamas', 'iso3'                                      => 'BHS', 'numcode' => 44),
            array('id' => 31,  'iso' => 'BT', 'name' => 'BHUTAN', 'country'                                       => 'Bhutan', 'iso3'                                       => 'BTN', 'numcode' => 64),
            array('id' => 32,  'iso' => 'BV', 'name' => 'BOUVET ISLAND', 'country'                                => 'Bouvet Island', 'iso3'                                => NULL, 'numcode'  => NULL),
            array('id' => 33,  'iso' => 'BW', 'name' => 'BOTSWANA', 'country'                                     => 'Botswana', 'iso3'                                     => 'BWA', 'numcode' => 72),
            array('id' => 34,  'iso' => 'BY', 'name' => 'BELARUS', 'country'                                      => 'Belarus', 'iso3'                                      => 'BLR', 'numcode' => 112),
            array('id' => 35,  'iso' => 'BZ', 'name' => 'BELIZE', 'country'                                       => 'Belize', 'iso3'                                       => 'BLZ', 'numcode' => 84),
            array('id' => 36,  'iso' => 'CA', 'name' => 'CANADA', 'country'                                       => 'Canada', 'iso3'                                       => 'CAN', 'numcode' => 124),
            array('id' => 37,  'iso' => 'CC', 'name' => 'COCOS (KEELING) ISLANDS', 'country'                      => 'Cocos (Keeling) Islands', 'iso3'                      => NULL, 'numcode'  => NULL),
            array('id' => 38,  'iso' => 'CD', 'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'country'        => 'Congo, the Democratic Republic of the', 'iso3'        => 'COD', 'numcode' => 180),
            array('id' => 39,  'iso' => 'CF', 'name' => 'CENTRAL AFRICAN REPUBLIC', 'country'                     => 'Central African Republic', 'iso3'                     => 'CAF', 'numcode' => 140),
            array('id' => 40,  'iso' => 'CG', 'name' => 'CONGO', 'country'                                        => 'Congo', 'iso3'                                        => 'COG', 'numcode' => 178),
            array('id' => 41,  'iso' => 'CH', 'name' => 'SWITZERLAND', 'country'                                  => 'Switzerland', 'iso3'                                  => 'CHE', 'numcode' => 756),
            array('id' => 42,  'iso' => 'CI', 'name' => 'COTE D\'IVOIRE', 'country'                               => 'Cote D\'Ivoire', 'iso3'                               => 'CIV', 'numcode' => 384),
            array('id' => 43,  'iso' => 'CK', 'name' => 'COOK ISLANDS', 'country'                                 => 'Cook Islands', 'iso3'                                 => 'COK', 'numcode' => 184),
            array('id' => 44,  'iso' => 'CL', 'name' => 'CHILE', 'country'                                        => 'Chile', 'iso3'                                        => 'CHL', 'numcode' => 152),
            array('id' => 45,  'iso' => 'CM', 'name' => 'CAMEROON', 'country'                                     => 'Cameroon', 'iso3'                                     => 'CMR', 'numcode' => 120),
            array('id' => 46,  'iso' => 'CN', 'name' => 'CHINA', 'country'                                        => 'China', 'iso3'                                        => 'CHN', 'numcode' => 156),
            array('id' => 47,  'iso' => 'CO', 'name' => 'COLOMBIA', 'country'                                     => 'Colombia', 'iso3'                                     => 'COL', 'numcode' => 170),
            array('id' => 48,  'iso' => 'CR', 'name' => 'COSTA RICA', 'country'                                   => 'Costa Rica', 'iso3'                                   => 'CRI', 'numcode' => 188),
            array('id' => 49,  'iso' => 'CS', 'name' => 'SERBIA AND MONTENEGRO', 'country'                        => 'Serbia and Montenegro', 'iso3'                        => NULL, 'numcode'  => NULL),
            array('id' => 50,  'iso' => 'CU', 'name' => 'CUBA', 'country'                                         => 'Cuba', 'iso3'                                         => 'CUB', 'numcode' => 192),
            array('id' => 51,  'iso' => 'CV', 'name' => 'CAPE VERDE', 'country'                                   => 'Cape Verde', 'iso3'                                   => 'CPV', 'numcode' => 132),
            array('id' => 52,  'iso' => 'CX', 'name' => 'CHRISTMAS ISLAND', 'country'                             => 'Christmas Island', 'iso3'                             => NULL, 'numcode'  => NULL),
            array('id' => 53,  'iso' => 'CY', 'name' => 'CYPRUS', 'country'                                       => 'Cyprus', 'iso3'                                       => 'CYP', 'numcode' => 196),
            array('id' => 54,  'iso' => 'CZ', 'name' => 'CZECH REPUBLIC', 'country'                               => 'Czech Republic', 'iso3'                               => 'CZE', 'numcode' => 203),
            array('id' => 55,  'iso' => 'DE', 'name' => 'GERMANY', 'country'                                      => 'Germany', 'iso3'                                      => 'DEU', 'numcode' => 276),
            array('id' => 56,  'iso' => 'DJ', 'name' => 'DJIBOUTI', 'country'                                     => 'Djibouti', 'iso3'                                     => 'DJI', 'numcode' => 262),
            array('id' => 57,  'iso' => 'DK', 'name' => 'DENMARK', 'country'                                      => 'Denmark', 'iso3'                                      => 'DNK', 'numcode' => 208),
            array('id' => 58,  'iso' => 'DM', 'name' => 'DOMINICA', 'country'                                     => 'Dominica', 'iso3'                                     => 'DMA', 'numcode' => 212),
            array('id' => 59,  'iso' => 'DO', 'name' => 'DOMINICAN REPUBLIC', 'country'                           => 'Dominican Republic', 'iso3'                           => 'DOM', 'numcode' => 214),
            array('id' => 60,  'iso' => 'DZ', 'name' => 'ALGERIA', 'country'                                      => 'Algeria', 'iso3'                                      => 'DZA', 'numcode' => 12),
            array('id' => 61,  'iso' => 'EC', 'name' => 'ECUADOR', 'country'                                      => 'Ecuador', 'iso3'                                      => 'ECU', 'numcode' => 218),
            array('id' => 62,  'iso' => 'EE', 'name' => 'ESTONIA', 'country'                                      => 'Estonia', 'iso3'                                      => 'EST', 'numcode' => 233),
            array('id' => 63,  'iso' => 'EG', 'name' => 'EGYPT', 'country'                                        => 'Egypt', 'iso3'                                        => 'EGY', 'numcode' => 818),
            array('id' => 64,  'iso' => 'EH', 'name' => 'WESTERN SAHARA', 'country'                               => 'Western Sahara', 'iso3'                               => 'ESH', 'numcode' => 732),
            array('id' => 65,  'iso' => 'ER', 'name' => 'ERITREA', 'country'                                      => 'Eritrea', 'iso3'                                      => 'ERI', 'numcode' => 232),
            array('id' => 66,  'iso' => 'ES', 'name' => 'SPAIN', 'country'                                        => 'Spain', 'iso3'                                        => 'ESP', 'numcode' => 724),
            array('id' => 67,  'iso' => 'ET', 'name' => 'ETHIOPIA', 'country'                                     => 'Ethiopia', 'iso3'                                     => 'ETH', 'numcode' => 231),
            array('id' => 68,  'iso' => 'FI', 'name' => 'FINLAND', 'country'                                      => 'Finland', 'iso3'                                      => 'FIN', 'numcode' => 246),
            array('id' => 69,  'iso' => 'FJ', 'name' => 'FIJI', 'country'                                         => 'Fiji', 'iso3'                                         => 'FJI', 'numcode' => 242),
            array('id' => 70,  'iso' => 'FK', 'name' => 'FALKLAND ISLANDS (MALVINAS)', 'country'                  => 'Falkland Islands (Malvinas)', 'iso3'                  => 'FLK', 'numcode' => 238),
            array('id' => 71,  'iso' => 'FM', 'name' => 'MICRONESIA, FEDERATED STATES OF', 'country'              => 'Micronesia, Federated States of', 'iso3'              => 'FSM', 'numcode' => 583),
            array('id' => 72,  'iso' => 'FO', 'name' => 'FAROE ISLANDS', 'country'                                => 'Faroe Islands', 'iso3'                                => 'FRO', 'numcode' => 234),
            array('id' => 73,  'iso' => 'FR', 'name' => 'FRANCE', 'country'                                       => 'France', 'iso3'                                       => 'FRA', 'numcode' => 250),
            array('id' => 74,  'iso' => 'GA', 'name' => 'GABON', 'country'                                        => 'Gabon', 'iso3'                                        => 'GAB', 'numcode' => 266),
            array('id' => 75,  'iso' => 'GB', 'name' => 'UNITED KINGDOM', 'country'                               => 'United Kingdom', 'iso3'                               => 'GBR', 'numcode' => 826),
            array('id' => 76,  'iso' => 'GD', 'name' => 'GRENADA', 'country'                                      => 'Grenada', 'iso3'                                      => 'GRD', 'numcode' => 308),
            array('id' => 77,  'iso' => 'GE', 'name' => 'GEORGIA', 'country'                                      => 'Georgia', 'iso3'                                      => 'GEO', 'numcode' => 268),
            array('id' => 78,  'iso' => 'GF', 'name' => 'FRENCH GUIANA', 'country'                                => 'French Guiana', 'iso3'                                => 'GUF', 'numcode' => 254),
            array('id' => 79,  'iso' => 'GH', 'name' => 'GHANA', 'country'                                        => 'Ghana', 'iso3'                                        => 'GHA', 'numcode' => 288),
            array('id' => 80,  'iso' => 'GI', 'name' => 'GIBRALTAR', 'country'                                    => 'Gibraltar', 'iso3'                                    => 'GIB', 'numcode' => 292),
            array('id' => 81,  'iso' => 'GL', 'name' => 'GREENLAND', 'country'                                    => 'Greenland', 'iso3'                                    => 'GRL', 'numcode' => 304),
            array('id' => 82,  'iso' => 'GM', 'name' => 'GAMBIA', 'country'                                       => 'Gambia', 'iso3'                                       => 'GMB', 'numcode' => 270),
            array('id' => 83,  'iso' => 'GN', 'name' => 'GUINEA', 'country'                                       => 'Guinea', 'iso3'                                       => 'GIN', 'numcode' => 324),
            array('id' => 84,  'iso' => 'GP', 'name' => 'GUADELOUPE', 'country'                                   => 'Guadeloupe', 'iso3'                                   => 'GLP', 'numcode' => 312),
            array('id' => 85,  'iso' => 'GQ', 'name' => 'EQUATORIAL GUINEA', 'country'                            => 'Equatorial Guinea', 'iso3'                            => 'GNQ', 'numcode' => 226),
            array('id' => 86,  'iso' => 'GR', 'name' => 'GREECE', 'country'                                       => 'Greece', 'iso3'                                       => 'GRC', 'numcode' => 300),
            array('id' => 87,  'iso' => 'GS', 'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'country' => 'South Georgia and the South Sandwich Islands', 'iso3' => NULL, 'numcode'  => NULL),
            array('id' => 88,  'iso' => 'GT', 'name' => 'GUATEMALA', 'country'                                    => 'Guatemala', 'iso3'                                    => 'GTM', 'numcode' => 320),
            array('id' => 89,  'iso' => 'GU', 'name' => 'GUAM', 'country'                                         => 'Guam', 'iso3'                                         => 'GUM', 'numcode' => 316),
            array('id' => 90,  'iso' => 'GW', 'name' => 'GUINEA-BISSAU', 'country'                                => 'Guinea-Bissau', 'iso3'                                => 'GNB', 'numcode' => 624),
            array('id' => 91,  'iso' => 'GY', 'name' => 'GUYANA', 'country'                                       => 'Guyana', 'iso3'                                       => 'GUY', 'numcode' => 328),
            array('id' => 92,  'iso' => 'HK', 'name' => 'HONG KONG', 'country'                                    => 'Hong Kong', 'iso3'                                    => 'HKG', 'numcode' => 344),
            array('id' => 93,  'iso' => 'HM', 'name' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'country'            => 'Heard Island and Mcdonald Islands', 'iso3'            => NULL, 'numcode'  => NULL),
            array('id' => 94,  'iso' => 'HN', 'name' => 'HONDURAS', 'country'                                     => 'Honduras', 'iso3'                                     => 'HND', 'numcode' => 340),
            array('id' => 95,  'iso' => 'HR', 'name' => 'CROATIA', 'country'                                      => 'Croatia', 'iso3'                                      => 'HRV', 'numcode' => 191),
            array('id' => 96,  'iso' => 'HT', 'name' => 'HAITI', 'country'                                        => 'Haiti', 'iso3'                                        => 'HTI', 'numcode' => 332),
            array('id' => 97,  'iso' => 'HU', 'name' => 'HUNGARY', 'country'                                      => 'Hungary', 'iso3'                                      => 'HUN', 'numcode' => 348),
            array('id' => 98,  'iso' => 'ID', 'name' => 'INDONESIA', 'country'                                    => 'Indonesia', 'iso3'                                    => 'IDN', 'numcode' => 360),
            array('id' => 99,  'iso' => 'IE', 'name' => 'IRELAND', 'country'                                      => 'Ireland', 'iso3'                                      => 'IRL', 'numcode' => 372),
            array('id' => 100, 'iso' => 'IL', 'name' => 'ISRAEL',  'country'                                      => 'Israel', 'iso3'                                       => 'ISR', 'numcode' => 376),
            array('id' => 101, 'iso' => 'IN', 'name' => 'INDIA',  'country'                                       => 'India', 'iso3'                                        => 'IND', 'numcode' => 356),
            array('id' => 102, 'iso' => 'IO', 'name' => 'BRITISH INDIAN OCEAN TERRITORY', 'country'               => 'British Indian Ocean Territory', 'iso3'               => NULL, 'numcode'  => NULL),
            array('id' => 103, 'iso' => 'IQ', 'name' => 'IRAQ', 'country'                                         => 'Iraq', 'iso3'                                         => 'IRQ', 'numcode' => 368),
            array('id' => 104, 'iso' => 'IR', 'name' => 'IRAN, ISLAMIC REPUBLIC OF', 'country'                    => 'Iran, Islamic Republic of', 'iso3'                    => 'IRN', 'numcode' => 364),
            array('id' => 105, 'iso' => 'IS', 'name' => 'ICELAND', 'country'                                      => 'Iceland', 'iso3'                                      => 'ISL', 'numcode' => 352),
            array('id' => 106, 'iso' => 'IT', 'name' => 'ITALY', 'country'                                        => 'Italy', 'iso3'                                        => 'ITA', 'numcode' => 380),
            array('id' => 107, 'iso' => 'JM', 'name' => 'JAMAICA', 'country'                                      => 'Jamaica', 'iso3'                                      => 'JAM', 'numcode' => 388),
            array('id' => 108, 'iso' => 'JO', 'name' => 'JORDAN', 'country'                                       => 'Jordan', 'iso3'                                       => 'JOR', 'numcode' => 400),
            array('id' => 109, 'iso' => 'JP', 'name' => 'JAPAN', 'country'                                        => 'Japan', 'iso3'                                        => 'JPN', 'numcode' => 392),
            array('id' => 110, 'iso' => 'KE', 'name' => 'KENYA', 'country'                                        => 'Kenya', 'iso3'                                        => 'KEN', 'numcode' => 404),
            array('id' => 111, 'iso' => 'KG', 'name' => 'KYRGYZSTAN', 'country'                                   => 'Kyrgyzstan', 'iso3'                                   => 'KGZ', 'numcode' => 417),
            array('id' => 112, 'iso' => 'KH', 'name' => 'CAMBODIA', 'country'                                     => 'Cambodia', 'iso3'                                     => 'KHM', 'numcode' => 116),
            array('id' => 113, 'iso' => 'KI', 'name' => 'KIRIBATI', 'country'                                     => 'Kiribati', 'iso3'                                     => 'KIR', 'numcode' => 296),
            array('id' => 114, 'iso' => 'KM', 'name' => 'COMOROS', 'country'                                      => 'Comoros', 'iso3'                                      => 'COM', 'numcode' => 174),
            array('id' => 115, 'iso' => 'KN', 'name' => 'SAINT KITTS AND NEVIS', 'country'                        => 'Saint Kitts and Nevis', 'iso3'                        => 'KNA', 'numcode' => 659),
            array('id' => 116, 'iso' => 'KP', 'name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'country'      => 'Korea, Democratic People\'s Republic of', 'iso3'      => 'PRK', 'numcode' => 408),
            array('id' => 117, 'iso' => 'KR', 'name' => 'KOREA, REPUBLIC OF', 'country'                           => 'Korea, Republic of', 'iso3'                           => 'KOR', 'numcode' => 410),
            array('id' => 118, 'iso' => 'KW', 'name' => 'KUWAIT', 'country'                                       => 'Kuwait', 'iso3'                                       => 'KWT', 'numcode' => 414),
            array('id' => 119, 'iso' => 'KY', 'name' => 'CAYMAN ISLANDS', 'country'                               => 'Cayman Islands', 'iso3'                               => 'CYM', 'numcode' => 136),
            array('id' => 120, 'iso' => 'KZ', 'name' => 'KAZAKHSTAN', 'country'                                   => 'Kazakhstan', 'iso3'                                   => 'KAZ', 'numcode' => 398),
            array('id' => 121, 'iso' => 'LA', 'name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'country'            => 'Lao People\'s Democratic Republic', 'iso3'            => 'LAO', 'numcode' => 418),
            array('id' => 122, 'iso' => 'LB', 'name' => 'LEBANON', 'country'                                      => 'Lebanon', 'iso3'                                      => 'LBN', 'numcode' => 422),
            array('id' => 123, 'iso' => 'LC', 'name' => 'SAINT LUCIA', 'country'                                  => 'Saint Lucia', 'iso3'                                  => 'LCA', 'numcode' => 662),
            array('id' => 124, 'iso' => 'LI', 'name' => 'LIECHTENSTEIN', 'country'                                => 'Liechtenstein', 'iso3'                                => 'LIE', 'numcode' => 438),
            array('id' => 125, 'iso' => 'LK', 'name' => 'SRI LANKA', 'country'                                    => 'Sri Lanka', 'iso3'                                    => 'LKA', 'numcode' => 144),
            array('id' => 126, 'iso' => 'LR', 'name' => 'LIBERIA', 'country'                                      => 'Liberia', 'iso3'                                      => 'LBR', 'numcode' => 430),
            array('id' => 127, 'iso' => 'LS', 'name' => 'LESOTHO', 'country'                                      => 'Lesotho', 'iso3'                                      => 'LSO', 'numcode' => 426),
            array('id' => 128, 'iso' => 'LT', 'name' => 'LITHUANIA', 'country'                                    => 'Lithuania', 'iso3'                                    => 'LTU', 'numcode' => 440),
            array('id' => 129, 'iso' => 'LU', 'name' => 'LUXEMBOURG', 'country'                                   => 'Luxembourg', 'iso3'                                   => 'LUX', 'numcode' => 442),
            array('id' => 130, 'iso' => 'LV', 'name' => 'LATVIA', 'country'                                       => 'Latvia', 'iso3'                                       => 'LVA', 'numcode' => 428),
            array('id' => 131, 'iso' => 'LY', 'name' => 'LIBYAN ARAB JAMAHIRIYA', 'country'                       => 'Libyan Arab Jamahiriya', 'iso3'                       => 'LBY', 'numcode' => 434),
            array('id' => 132, 'iso' => 'MA', 'name' => 'MOROCCO', 'country'                                      => 'Morocco', 'iso3'                                      => 'MAR', 'numcode' => 504),
            array('id' => 133, 'iso' => 'MC', 'name' => 'MONACO', 'country'                                       => 'Monaco', 'iso3'                                       => 'MCO', 'numcode' => 492),
            array('id' => 134, 'iso' => 'MD', 'name' => 'MOLDOVA, REPUBLIC OF', 'country'                         => 'Moldova, Republic of', 'iso3'                         => 'MDA', 'numcode' => 498),
            array('id' => 135, 'iso' => 'MG', 'name' => 'MADAGASCAR', 'country'                                   => 'Madagascar', 'iso3'                                   => 'MDG', 'numcode' => 450),
            array('id' => 136, 'iso' => 'MH', 'name' => 'MARSHALL ISLANDS', 'country'                             => 'Marshall Islands', 'iso3'                             => 'MHL', 'numcode' => 584),
            array('id' => 137, 'iso' => 'MK', 'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'country'   => 'Macedonia, the Former Yugoslav Republic of', 'iso3'   => 'MKD', 'numcode' => 807),
            array('id' => 138, 'iso' => 'ML', 'name' => 'MALI', 'country'                                         => 'Mali', 'iso3'                                         => 'MLI', 'numcode' => 466),
            array('id' => 139, 'iso' => 'MM', 'name' => 'MYANMAR', 'country'                                      => 'Myanmar', 'iso3'                                      => 'MMR', 'numcode' => 104),
            array('id' => 140, 'iso' => 'MN', 'name' => 'MONGOLIA', 'country'                                     => 'Mongolia', 'iso3'                                     => 'MNG', 'numcode' => 496),
            array('id' => 141, 'iso' => 'MO', 'name' => 'MACAO', 'country'                                        => 'Macao', 'iso3'                                        => 'MAC', 'numcode' => 446),
            array('id' => 142, 'iso' => 'MP', 'name' => 'NORTHERN MARIANA ISLANDS', 'country'                     => 'Northern Mariana Islands', 'iso3'                     => 'MNP', 'numcode' => 580),
            array('id' => 143, 'iso' => 'MQ', 'name' => 'MARTINIQUE', 'country'                                   => 'Martinique', 'iso3'                                   => 'MTQ', 'numcode' => 474),
            array('id' => 144, 'iso' => 'MR', 'name' => 'MAURITANIA', 'country'                                   => 'Mauritania', 'iso3'                                   => 'MRT', 'numcode' => 478),
            array('id' => 145, 'iso' => 'MS', 'name' => 'MONTSERRAT', 'country'                                   => 'Montserrat', 'iso3'                                   => 'MSR', 'numcode' => 500),
            array('id' => 146, 'iso' => 'MT', 'name' => 'MALTA', 'country'                                        => 'Malta', 'iso3'                                        => 'MLT', 'numcode' => 470),
            array('id' => 147, 'iso' => 'MU', 'name' => 'MAURITIUS', 'country'                                    => 'Mauritius', 'iso3'                                    => 'MUS', 'numcode' => 480),
            array('id' => 148, 'iso' => 'MV', 'name' => 'MALDIVES', 'country'                                     => 'Maldives', 'iso3'                                     => 'MDV', 'numcode' => 462),
            array('id' => 149, 'iso' => 'MW', 'name' => 'MALAWI', 'country'                                       => 'Malawi', 'iso3'                                       => 'MWI', 'numcode' => 454),
            array('id' => 150, 'iso' => 'MX', 'name' => 'MEXICO', 'country'                                       => 'Mexico', 'iso3'                                       => 'MEX', 'numcode' => 484),
            array('id' => 151, 'iso' => 'MY', 'name' => 'MALAYSIA', 'country'                                     => 'Malaysia', 'iso3'                                     => 'MYS', 'numcode' => 458),
            array('id' => 152, 'iso' => 'MZ', 'name' => 'MOZAMBIQUE', 'country'                                   => 'Mozambique', 'iso3'                                   => 'MOZ', 'numcode' => 508),
            array('id' => 153, 'iso' => 'NA', 'name' => 'NAMIBIA', 'country'                                      => 'Namibia', 'iso3'                                      => 'NAM', 'numcode' => 516),
            array('id' => 154, 'iso' => 'NC', 'name' => 'NEW CALEDONIA', 'country'                                => 'New Caledonia', 'iso3'                                => 'NCL', 'numcode' => 540),
            array('id' => 155, 'iso' => 'NE', 'name' => 'NIGER', 'country'                                        => 'Niger', 'iso3'                                        => 'NER', 'numcode' => 562),
            array('id' => 156, 'iso' => 'NF', 'name' => 'NORFOLK ISLAND', 'country'                               => 'Norfolk Island', 'iso3'                               => 'NFK', 'numcode' => 574),
            array('id' => 157, 'iso' => 'NG', 'name' => 'NIGERIA', 'country'                                      => 'Nigeria', 'iso3'                                      => 'NGA', 'numcode' => 566),
            array('id' => 158, 'iso' => 'NI', 'name' => 'NICARAGUA', 'country'                                    => 'Nicaragua', 'iso3'                                    => 'NIC', 'numcode' => 558),
            array('id' => 159, 'iso' => 'NL', 'name' => 'NETHERLANDS', 'country'                                  => 'Netherlands', 'iso3'                                  => 'NLD', 'numcode' => 528),
            array('id' => 160, 'iso' => 'NO', 'name' => 'NORWAY', 'country'                                       => 'Norway', 'iso3'                                       => 'NOR', 'numcode' => 578),
            array('id' => 161, 'iso' => 'NP', 'name' => 'NEPAL', 'country'                                        => 'Nepal', 'iso3'                                        => 'NPL', 'numcode' => 524),
            array('id' => 162, 'iso' => 'NR', 'name' => 'NAURU', 'country'                                        => 'Nauru', 'iso3'                                        => 'NRU', 'numcode' => 520),
            array('id' => 163, 'iso' => 'NU', 'name' => 'NIUE', 'country'                                         => 'Niue', 'iso3'                                         => 'NIU', 'numcode' => 570),
            array('id' => 164, 'iso' => 'NZ', 'name' => 'NEW ZEALAND', 'country'                                  => 'New Zealand', 'iso3'                                  => 'NZL', 'numcode' => 554),
            array('id' => 165, 'iso' => 'OM', 'name' => 'OMAN', 'country'                                         => 'Oman', 'iso3'                                         => 'OMN', 'numcode' => 512),
            array('id' => 166, 'iso' => 'PA', 'name' => 'PANAMA', 'country'                                       => 'Panama', 'iso3'                                       => 'PAN', 'numcode' => 591),
            array('id' => 167, 'iso' => 'PE', 'name' => 'PERU', 'country'                                         => 'Peru', 'iso3'                                         => 'PER', 'numcode' => 604),
            array('id' => 168, 'iso' => 'PF', 'name' => 'FRENCH POLYNESIA', 'country'                             => 'French Polynesia', 'iso3'                             => 'PYF', 'numcode' => 258),
            array('id' => 169, 'iso' => 'PG', 'name' => 'PAPUA NEW GUINEA', 'country'                             => 'Papua New Guinea', 'iso3'                             => 'PNG', 'numcode' => 598),
            array('id' => 170, 'iso' => 'PH', 'name' => 'PHILIPPINES', 'country'                                  => 'Philippines', 'iso3'                                  => 'PHL', 'numcode' => 608),
            array('id' => 171, 'iso' => 'PK', 'name' => 'PAKISTAN', 'country'                                     => 'Pakistan', 'iso3'                                     => 'PAK', 'numcode' => 586),
            array('id' => 172, 'iso' => 'PL', 'name' => 'POLAND', 'country'                                       => 'Poland', 'iso3'                                       => 'POL', 'numcode' => 616),
            array('id' => 173, 'iso' => 'PM', 'name' => 'SAINT PIERRE AND MIQUELON', 'country'                    => 'Saint Pierre and Miquelon', 'iso3'                    => 'SPM', 'numcode' => 666),
            array('id' => 174, 'iso' => 'PN', 'name' => 'PITCAIRN', 'country'                                     => 'Pitcairn', 'iso3'                                     => 'PCN', 'numcode' => 612),
            array('id' => 175, 'iso' => 'PR', 'name' => 'PUERTO RICO', 'country'                                  => 'Puerto Rico', 'iso3'                                  => 'PRI', 'numcode' => 630),
            array('id' => 176, 'iso' => 'PS', 'name' => 'PALESTINIAN TERRITORY, OCCUPIED', 'country'              => 'Palestinian Territory, Occupied', 'iso3'              => NULL, 'numcode'  => NULL),
            array('id' => 177, 'iso' => 'PT', 'name' => 'PORTUGAL', 'country'                                     => 'Portugal', 'iso3'                                     => 'PRT', 'numcode' => 620),
            array('id' => 178, 'iso' => 'PW', 'name' => 'PALAU', 'country'                                        => 'Palau', 'iso3'                                        => 'PLW', 'numcode' => 585),
            array('id' => 179, 'iso' => 'PY', 'name' => 'PARAGUAY', 'country'                                     => 'Paraguay', 'iso3'                                     => 'PRY', 'numcode' => 600),
            array('id' => 180, 'iso' => 'QA', 'name' => 'QATAR', 'country'                                        => 'Qatar', 'iso3'                                        => 'QAT', 'numcode' => 634),
            array('id' => 181, 'iso' => 'RE', 'name' => 'REUNION', 'country'                                      => 'Reunion', 'iso3'                                      => 'REU', 'numcode' => 638),
            array('id' => 182, 'iso' => 'RO', 'name' => 'ROMANIA', 'country'                                      => 'Romania', 'iso3'                                      => 'ROM', 'numcode' => 642),
            array('id' => 183, 'iso' => 'RU', 'name' => 'RUSSIAN FEDERATION', 'country'                           => 'Russian Federation', 'iso3'                           => 'RUS', 'numcode' => 643),
            array('id' => 184, 'iso' => 'RW', 'name' => 'RWANDA', 'country'                                       => 'Rwanda', 'iso3'                                       => 'RWA', 'numcode' => 646),
            array('id' => 185, 'iso' => 'SA', 'name' => 'SAUDI ARABIA', 'country'                                 => 'Saudi Arabia', 'iso3'                                 => 'SAU', 'numcode' => 682),
            array('id' => 186, 'iso' => 'SB', 'name' => 'SOLOMON ISLANDS', 'country'                              => 'Solomon Islands', 'iso3'                              => 'SLB', 'numcode' => 90),
            array('id' => 187, 'iso' => 'SC', 'name' => 'SEYCHELLES', 'country'                                   => 'Seychelles', 'iso3'                                   => 'SYC', 'numcode' => 690),
            array('id' => 188, 'iso' => 'SD', 'name' => 'SUDAN', 'country'                                        => 'Sudan', 'iso3'                                        => 'SDN', 'numcode' => 736),
            array('id' => 189, 'iso' => 'SE', 'name' => 'SWEDEN', 'country'                                       => 'Sweden', 'iso3'                                       => 'SWE', 'numcode' => 752),
            array('id' => 190, 'iso' => 'SG', 'name' => 'SINGAPORE', 'country'                                    => 'Singapore', 'iso3'                                    => 'SGP', 'numcode' => 702),
            array('id' => 191, 'iso' => 'SH', 'name' => 'SAINT HELENA', 'country'                                 => 'Saint Helena', 'iso3'                                 => 'SHN', 'numcode' => 654),
            array('id' => 192, 'iso' => 'SI', 'name' => 'SLOVENIA', 'country'                                     => 'Slovenia', 'iso3'                                     => 'SVN', 'numcode' => 705),
            array('id' => 193, 'iso' => 'SJ', 'name' => 'SVALBARD AND JAN MAYEN', 'country'                       => 'Svalbard and Jan Mayen', 'iso3'                       => 'SJM', 'numcode' => 744),
            array('id' => 194, 'iso' => 'SK', 'name' => 'SLOVAKIA', 'country'                                     => 'Slovakia', 'iso3'                                     => 'SVK', 'numcode' => 703),
            array('id' => 195, 'iso' => 'SL', 'name' => 'SIERRA LEONE', 'country'                                 => 'Sierra Leone', 'iso3'                                 => 'SLE', 'numcode' => 694),
            array('id' => 196, 'iso' => 'SM', 'name' => 'SAN MARINO', 'country'                                   => 'San Marino', 'iso3'                                   => 'SMR', 'numcode' => 674),
            array('id' => 197, 'iso' => 'SN', 'name' => 'SENEGAL', 'country'                                      => 'Senegal', 'iso3'                                      => 'SEN', 'numcode' => 686),
            array('id' => 198, 'iso' => 'SO', 'name' => 'SOMALIA', 'country'                                      => 'Somalia', 'iso3'                                      => 'SOM', 'numcode' => 706),
            array('id' => 199, 'iso' => 'SR', 'name' => 'SURINAME', 'country'                                     => 'Suriname', 'iso3'                                     => 'SUR', 'numcode' => 740),
            array('id' => 200, 'iso' => 'ST', 'name' => 'SAO TOME AND PRINCIPE', 'country'                        => 'Sao Tome and Principe', 'iso3'                        => 'STP', 'numcode' => 678),
            array('id' => 201, 'iso' => 'SV', 'name' => 'EL SALVADOR', 'country'                                  => 'El Salvador', 'iso3'                                  => 'SLV', 'numcode' => 222),
            array('id' => 202, 'iso' => 'SY', 'name' => 'SYRIAN ARAB REPUBLIC', 'country'                         => 'Syrian Arab Republic', 'iso3'                         => 'SYR', 'numcode' => 760),
            array('id' => 203, 'iso' => 'SZ', 'name' => 'SWAZILAND', 'country'                                    => 'Swaziland', 'iso3'                                    => 'SWZ', 'numcode' => 748),
            array('id' => 204, 'iso' => 'TC', 'name' => 'TURKS AND CAICOS ISLANDS', 'country'                     => 'Turks and Caicos Islands', 'iso3'                     => 'TCA', 'numcode' => 796),
            array('id' => 205, 'iso' => 'TD', 'name' => 'CHAD', 'country'                                         => 'Chad', 'iso3'                                         => 'TCD', 'numcode' => 148),
            array('id' => 206, 'iso' => 'TF', 'name' => 'FRENCH SOUTHERN TERRITORIES', 'country'                  => 'French Southern Territories','iso3'                   => NULL, 'numcode'  => NULL),
            array('id' => 207, 'iso' => 'TG', 'name' => 'TOGO', 'country'                                         => 'Togo', 'iso3'                                         => 'TGO', 'numcode' => 768),
            array('id' => 208, 'iso' => 'TH', 'name' => 'THAILAND', 'country'                                     => 'Thailand', 'iso3'                                     => 'THA', 'numcode' => 764),
            array('id' => 209, 'iso' => 'TJ', 'name' => 'TAJIKISTAN', 'country'                                   => 'Tajikistan', 'iso3'                                   => 'TJK', 'numcode' => 762),
            array('id' => 210, 'iso' => 'TK', 'name' => 'TOKELAU', 'country'                                      => 'Tokelau', 'iso3'                                      => 'TKL', 'numcode' => 772),
            array('id' => 211, 'iso' => 'TL', 'name' => 'TIMOR-LESTE', 'country'                                  => 'Timor-Leste', 'iso3'                                  => NULL, 'numcode'  => NULL),
            array('id' => 212, 'iso' => 'TM', 'name' => 'TURKMENISTAN', 'country'                                 => 'Turkmenistan', 'iso3'                                 => 'TKM', 'numcode' => 795),
            array('id' => 213, 'iso' => 'TN', 'name' => 'TUNISIA', 'country'                                      => 'Tunisia', 'iso3'                                      => 'TUN', 'numcode' => 788),
            array('id' => 214, 'iso' => 'TO', 'name' => 'TONGA', 'country'                                        => 'Tonga', 'iso3'                                        => 'TON', 'numcode' => 776),
            array('id' => 215, 'iso' => 'TR', 'name' => 'TURKEY', 'country'                                       => 'Turkey', 'iso3'                                       => 'TUR', 'numcode' => 792),
            array('id' => 216, 'iso' => 'TT', 'name' => 'TRINIDAD AND TOBAGO', 'country'                          => 'Trinidad and Tobago', 'iso3'                          => 'TTO', 'numcode' => 780),
            array('id' => 217, 'iso' => 'TV', 'name' => 'TUVALU', 'country'                                       => 'Tuvalu', 'iso3'                                       => 'TUV', 'numcode' => 798),
            array('id' => 218, 'iso' => 'TW', 'name' => 'TAIWAN, PROVINCE OF CHINA',  'country'                   => 'Taiwan, Province of China', 'iso3'                    => 'TWN', 'numcode' => 158),
            array('id' => 219, 'iso' => 'TZ', 'name' => 'TANZANIA, UNITED REPUBLIC OF', 'country'                 => 'Tanzania, United Republic of', 'iso3'                 => 'TZA', 'numcode' => 834),
            array('id' => 220, 'iso' => 'UA', 'name' => 'UKRAINE', 'country'                                      => 'Ukraine', 'iso3'                                      => 'UKR', 'numcode' => 804),
            array('id' => 221, 'iso' => 'UG', 'name' => 'UGANDA', 'country'                                       => 'Uganda', 'iso3'                                       => 'UGA', 'numcode' => 800),
            array('id' => 222, 'iso' => 'UM', 'name' => 'UNITED STATES MINOR OUTLYING ISLANDS', 'country'         => 'United States Minor Outlying Islands', 'iso3'         => NULL, 'numcode'  => NULL),
            array('id' => 223, 'iso' => 'US', 'name' => 'UNITED STATES', 'country'                                => 'United States', 'iso3'                                => 'USA', 'numcode' => 840),
            array('id' => 224, 'iso' => 'UY', 'name' => 'URUGUAY', 'country'                                      => 'Uruguay', 'iso3'                                      => 'URY', 'numcode' => 858),
            array('id' => 225, 'iso' => 'UZ', 'name' => 'UZBEKISTAN', 'country'                                   => 'Uzbekistan', 'iso3'                                   => 'UZB', 'numcode' => 860),
            array('id' => 226, 'iso' => 'VA', 'name' => 'HOLY SEE (VATICAN CITY STATE)', 'country'                => 'Holy See (Vatican City State)', 'iso3'                => 'VAT', 'numcode' => 336),
            array('id' => 227, 'iso' => 'VC', 'name' => 'SAINT VINCENT AND THE GRENADINES', 'country'             => 'Saint Vincent and the Grenadines', 'iso3'             => 'VCT', 'numcode' => 670),
            array('id' => 228, 'iso' => 'VE', 'name' => 'VENEZUELA', 'country'                                    => 'Venezuela', 'iso3'                                    => 'VEN', 'numcode' => 862),
            array('id' => 229, 'iso' => 'VG', 'name' => 'VIRGIN ISLANDS, BRITISH', 'country'                      => 'Virgin Islands, British', 'iso3'                      => 'VGB', 'numcode' => 92),
            array('id' => 230, 'iso' => 'VI', 'name' => 'VIRGIN ISLANDS, U.S.', 'country'                         => 'Virgin Islands, U.s.', 'iso3'                         => 'VIR', 'numcode' => 850),
            array('id' => 231, 'iso' => 'VN', 'name' => 'VIET NAM', 'country'                                     => 'Viet Nam', 'iso3'                                     => 'VNM', 'numcode' => 704),
            array('id' => 232, 'iso' => 'VU', 'name' => 'VANUATU', 'country'                                      => 'Vanuatu', 'iso3'                                      => 'VUT', 'numcode' => 548),
            array('id' => 233, 'iso' => 'WF', 'name' => 'WALLIS AND FUTUNA', 'country'                            => 'Wallis and Futuna', 'iso3'                            => 'WLF', 'numcode' => 876),
            array('id' => 234, 'iso' => 'WS', 'name' => 'SAMOA', 'country'                                        => 'Samoa', 'iso3'                                        => 'WSM', 'numcode' => 882),
            array('id' => 235, 'iso' => 'YE', 'name' => 'YEMEN', 'country'                                        => 'Yemen', 'iso3'                                        => 'YEM', 'numcode' => 887),
            array('id' => 236, 'iso' => 'YT', 'name' => 'MAYOTTE', 'country'                                      => 'Mayotte', 'iso3'                                      => NULL, 'numcode'  => NULL),
            array('id' => 237, 'iso' => 'ZA', 'name' => 'SOUTH AFRICA', 'country'                                 => 'South Africa', 'iso3'                                 => 'ZAF', 'numcode' => 710),
            array('id' => 238, 'iso' => 'ZM', 'name' => 'ZAMBIA', 'country'                                       => 'Zambia', 'iso3'                                       => 'ZMB', 'numcode' => 894),
            array('id' => 239, 'iso' => 'ZW', 'name' => 'ZIMBABWE', 'country'                                     => 'Zimbabwe', 'iso3'                                     => 'ZWE', 'numcode' => 716),
            array('id' => 240, 'iso' => 'TC', 'name' => 'Testsss', 'country'                                      => 'Test', 'iso3'                                         => 'Tc', 'numcode'  => 22),

        ));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
